name: study_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/book.png
    - assets/images/poor.png
    - assets/images/average.png
    - assets/images/excellent.png
    - assets/images/study.png
    - assets/audio/dissapointed.mp3
    - assets/audio/yeay.mp3
    - assets/audio/applause.mp3
